version: '3.7'
services:
  nodejs:
    container_name: is-backend
    restart: always
    build: .
    ports:
      - 4000:4000
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    command: npm run dev
    depends_on:
      - postgres
  postgres:
    container_name: is-postgres
    image: postgres:13-alpine
    ports:
      - 5444:5432
    volumes:
      - pg_data:/data/db
    logging:
      driver: none
    env_file:
        - ./.env.dev
volumes: 
  pg_data: